import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { sql } from "drizzle-orm";
import { PostgresBudgetStore, PostgresExpressStore, resultRows } from "../../server/security/postgresRateStore";
import { budgetKey, type Budget } from "../../server/security/operationLimitPolicy";
import { createOperationRateLimitTables } from "../../server/migrations/create-operation-rate-limit-tables";

test("real PostgreSQL: parallel admissions, two stores, hour/tenant/IP limits, leases and recovery",
  { skip: process.env.RUN_RATE_LIMIT_DB_TESTS !== "1" }, async () => {
    const { db } = await import("../../server/db");
    const execute = async (query: any) => db.execute(query);
    await createOperationRateLimitTables(execute);
    const first = new PostgresBudgetStore(execute), second = new PostgresBudgetStore(execute);
    const namespace = `synthetic-rate-test:${randomUUID()}`;
    const keys: string[] = [], leaseIds: string[] = [];
    const budget = (name: string, limit: number, windowMs = 60_000): Budget => {
      const key = budgetKey(namespace, name); keys.push(key);
      return { key, limit, windowMs, cost: 1 };
    };
    try {
      const actor = budget("actor-board", 10);
      const results = await Promise.all(Array.from({ length: 40 }, (_, i) =>
        (i % 2 ? first : second).consume([actor])));
      assert.equal(results.filter((r) => r.allowed).length, 10);
      const rows = resultRows(await execute(sql`SELECT hits FROM application_rate_counters WHERE bucket_key = ${actor.key}`));
      assert.equal(Number(rows[0].hits), 10, "parallel requests cannot overshoot");
      const recreated = new PostgresBudgetStore(execute);
      assert.equal((await recreated.consume([actor])).allowed, false, "process/store restart does not reset counters");
      await execute(sql`UPDATE application_rate_counters SET expires_at = clock_timestamp() - interval '1 second' WHERE bucket_key = ${actor.key}`);
      assert.equal((await recreated.consume([actor])).allowed, true);

      const burst = budget("burst", 100), hour = budget("hour", 2, 3_600_000);
      assert.equal((await first.consume([burst, hour])).allowed, true);
      assert.equal((await second.consume([burst, hour])).allowed, true);
      const denied = await first.consume([burst, hour]);
      assert.equal(denied.allowed, false);
      assert.ok(denied.retryAfter > 3500);
      assert.equal(Number(resultRows(await execute(sql`SELECT hits FROM application_rate_counters WHERE bucket_key = ${burst.key}`))[0].hits), 2,
        "failed multi-key admission does not consume another operation's budget");

      const tenant = budget("tenant", 2), ip = budget("ip", 2);
      for (let i = 0; i < 2; i++) assert.equal((await first.consume([budget(`user-${i}`, 10), tenant, ip])).allowed, true);
      assert.equal((await second.consume([budget("user-3", 10), tenant, ip])).allowed, false);

      const scope = { key: budgetKey(namespace, "concurrent"), limit: 2 }; keys.push(scope.key);
      const workBudget = budget("work", 20);
      for (let i = 0; i < 3; i++) leaseIds.push(randomUUID());
      assert.equal((await first.consume([workBudget], [scope], leaseIds[0])).allowed, true);
      assert.equal((await second.consume([workBudget], [scope], leaseIds[1])).allowed, true);
      assert.equal((await first.consume([workBudget], [scope], leaseIds[2])).allowed, false);
      await first.renew(leaseIds[0]);
      await second.release(leaseIds[0]);
      assert.equal((await second.consume([workBudget], [scope], leaseIds[2])).allowed, true);
      await execute(sql`UPDATE application_operation_leases SET expires_at = clock_timestamp() - interval '1 second'
        WHERE lease_id = ${leaseIds[1]}`);
      await assert.rejects(first.renew(leaseIds[1]), "expired leases must not resurrect");

      const legacyNamespace = `${namespace}:otp`;
      const legacyKey = budgetKey("express", legacyNamespace, "synthetic-ip"); keys.push(legacyKey);
      const legacyFirst = new PostgresExpressStore(execute, legacyNamespace);
      const legacySecond = new PostgresExpressStore(execute, legacyNamespace);
      assert.equal((await legacyFirst.increment("synthetic-ip")).totalHits, 1);
      assert.equal((await legacySecond.increment("synthetic-ip")).totalHits, 2);
      assert.ok((await legacyFirst.increment("synthetic-ip")).resetTime instanceof Date);
      await legacyFirst.resetKey("synthetic-ip");
    } finally {
      // Delete only keys generated by this synthetic test, never business data.
      for (const key of new Set(keys)) {
        await execute(sql`DELETE FROM application_rate_counters WHERE bucket_key = ${key}`);
        await execute(sql`DELETE FROM application_operation_leases WHERE scope_key = ${key}`);
      }
      for (const id of leaseIds) await first.release(id);
    }
  });
